version: '3.1'

services:
  db:
    image: postgres:alpine
    restart: always
    environment:
        POSTGRES_PASSWORD: zasxcdfv
        POSTGRES_USER: postgres
        POSTGRES_DB: postgres
    volumes:
      - ./postgresql:/var/lib/postgresql/data
    ports:
      - 5432:5432
